SET IDENTITY_INSERT [dbo].[Amenity] ON
INSERT INTO [dbo].[Amenity] ([ID], [AmenityName], [Type]) VALUES (1, N'Park Info Signs', N'a                   ')
INSERT INTO [dbo].[Amenity] ([ID], [AmenityName], [Type]) VALUES (2, N'Public Transit Stop', N'a                   ')
INSERT INTO [dbo].[Amenity] ([ID], [AmenityName], [Type]) VALUES (3, N'Parking', N'a                   ')
INSERT INTO [dbo].[Amenity] ([ID], [AmenityName], [Type]) VALUES (4, N'Sidewalks', N'a                   ')
INSERT INTO [dbo].[Amenity] ([ID], [AmenityName], [Type]) VALUES (5, N'Playground', N'f                   ')
INSERT INTO [dbo].[Amenity] ([ID], [AmenityName], [Type]) VALUES (6, N'Sport Field', N'f                   ')
INSERT INTO [dbo].[Amenity] ([ID], [AmenityName], [Type]) VALUES (7, N'Baseball Field', N'f                   ')
INSERT INTO [dbo].[Amenity] ([ID], [AmenityName], [Type]) VALUES (8, N'Swimming Pool', N'f                   ')
INSERT INTO [dbo].[Amenity] ([ID], [AmenityName], [Type]) VALUES (9, N'Splash Pad', N'f                   ')
INSERT INTO [dbo].[Amenity] ([ID], [AmenityName], [Type]) VALUES (10, N'Basketball Court', N'f                   ')
INSERT INTO [dbo].[Amenity] ([ID], [AmenityName], [Type]) VALUES (11, N'Tennis Court', N'f                   ')
INSERT INTO [dbo].[Amenity] ([ID], [AmenityName], [Type]) VALUES (12, N'Volleyball Court', N'f                   ')
INSERT INTO [dbo].[Amenity] ([ID], [AmenityName], [Type]) VALUES (13, N'Trail', N'f                   ')
INSERT INTO [dbo].[Amenity] ([ID], [AmenityName], [Type]) VALUES (14, N'Fitness Equipment', N'f                   ')
INSERT INTO [dbo].[Amenity] ([ID], [AmenityName], [Type]) VALUES (15, N'Skate Park', N'f                   ')
INSERT INTO [dbo].[Amenity] ([ID], [AmenityName], [Type]) VALUES (16, N'Off-leash Dog Park', N'f                   ')
INSERT INTO [dbo].[Amenity] ([ID], [AmenityName], [Type]) VALUES (17, N'Open/Green Space', N'f                   ')
INSERT INTO [dbo].[Amenity] ([ID], [AmenityName], [Type]) VALUES (18, N'Lake', N'a                   ')
INSERT INTO [dbo].[Amenity] ([ID], [AmenityName], [Type]) VALUES (19, N'Restrooms', N'a                   ')
INSERT INTO [dbo].[Amenity] ([ID], [AmenityName], [Type]) VALUES (20, N'Drinking Fountain', N'a                   ')
INSERT INTO [dbo].[Amenity] ([ID], [AmenityName], [Type]) VALUES (21, N'Benches', N'a                   ')
INSERT INTO [dbo].[Amenity] ([ID], [AmenityName], [Type]) VALUES (22, N'Picnic Tables', N'a                   ')
INSERT INTO [dbo].[Amenity] ([ID], [AmenityName], [Type]) VALUES (23, N'Trash Cans', N'a                   ')
INSERT INTO [dbo].[Amenity] ([ID], [AmenityName], [Type]) VALUES (24, N'Food/Vending Machines', N'a                   ')
INSERT INTO [dbo].[Amenity] ([ID], [AmenityName], [Type]) VALUES (25, N'Dog Waste Pick-up Bags', N'a                   ')
INSERT INTO [dbo].[Amenity] ([ID], [AmenityName], [Type]) VALUES (26, N'Lights', N'a                   ')
INSERT INTO [dbo].[Amenity] ([ID], [AmenityName], [Type]) VALUES (27, N'Emergency Devices', N'a                   ')
SET IDENTITY_INSERT [dbo].[Amenity] OFF
